### ISSUE TITLE
MyProjects is not a class (TypeError)

### ISSUE THREAD

**Issue by Kamakepar2029** [peelman/my_projects#16]
When starting redmine with plugin on, i get this error:

```bash
/usr/bin/ruby2.7: warning: shebang line ending with \r may cause problems
=> Booting Puma
=> Rails 6.1.6 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	63: from bin/rails:4:in `<main>'
	62: from bin/rails:4:in `require'
	61: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<top (required)>'
	60: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
	59: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
	58: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	57: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	56: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	55: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `perform'
	54: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `tap'
	53: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	52: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:39:in `start'
	51: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	50: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	49: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	48: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	47: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	46: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	45: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	44: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	43: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	42: from /var/lib/gems/2.7.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	41: from config.ru:3:in `block in <main>'
	40: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
	39: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	38: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
	37: from /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	36: from /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	35: from /opt/redmine/config/environment.rb:16:in `<top (required)>'
	34: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
	33: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
	32: from /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	31: from /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	30: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	29: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
	28: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
	27: from /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	26: from /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	25: from /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	24: from /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	23: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	22: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
	21: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
	20: from /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
	19: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
	18: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
	17: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
	16: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
	15: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
	14: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
	13: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
	12: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
	11: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
	10: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	 9: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	 8: from /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
	 7: from /opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
	 6: from /opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
	 5: from /opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
	 4: from /opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
	 3: from /opt/redmine/plugins/my_projects/init.rb:3:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	 1: from /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/opt/redmine/plugins/my_projects/lib/my_projects/view_hook_listener.rb:1:in `<top (required)>': MyProjects is not a class (TypeError)
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:48: previous definition of MyProjects was here
```

I need help to fix it. Please help.

**Comment by peelman** [comment]
This plugin is so far out of date, and I am so far removed from the Redmine project and community at this point, that I would be less than useful to you.

I would suggest seeking out a more up-to-date plugin with similar functionality, or asking somebody still active in the Redmine community for help.
